version: '3.8'

services:
  web-dashboard:
    build: .
    container_name: ajaib-web
    command: ["python", "-u", "server.py"]
    restart: always
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
      - ./watchlist.json:/app/watchlist.json
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ajaib-web.rule=Host(`sinyal.bintangmaulana.my.id`)"
      - "traefik.http.services.ajaib-web.loadbalancer.server.port=5000"
      - "traefik.http.routers.ajaib-web.entrypoints=websecure"
      - "traefik.http.routers.ajaib-web.tls.certresolver=letsencrypt"

  telegram-bot:
    build: .
    container_name: ajaib-bot
    command: ["python", "-u", "bot_telegram_v4_1.py"]
    restart: always
    env_file:
      - .env
    volumes:
      - ./watchlist.json:/app/watchlist.json
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  sqlite_data:
